### ISSUE TITLE
Organizar os dados

### ISSUE THREAD

**Issue by issilva5** [issilva5/coding_the_matrix_lab1#3]
Pegar os arquivos de dados que estão em https://github.com/thiagomanel/fmcc2/tree/master/vetores/similaridade/congresso/data/raw

e unir num único csv no formato:
id_deputado, partido, estado, voto1, voto2, ...

acho que a maneira mais fácil de fazer isso é usando R.

**Comment by ceciliakemiac** [comment]
pela quantidade de votos vai ser umas 800 colunas, é assim mesmo?

**Comment by issilva5** [comment]
sim sim, no código isso vira um array de 800 posições, relativamente pequeno

**Comment by issilva5** [comment]
Para pegar o nome e o estado do deputado, se for em R, recomendo usar:

`library(jsonlite)`
`deputado <- fromJSON("https://dadosabertos.camara.leg.br/api/v2/deputados/<id_deputado>")`
`Nome <- deputado$dados$ultimoStatus$nomeEleitoral`
`UF <- deputado$dados$ultimoStatus$siglaUf`
